server.port=8080

#  Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/hospital_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#  Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#  JWT
app.jwt.secret=HospitalAppSecretKey2024_VeryLongSecretKeyForSecurity
app.jwt.expiration=86400000
